# 基本站点信息
title: 谢栩瀚
tagline: 这是我的个人网站，用于放置我的简历与作品集
description: 一个Blender 3D场景设计师。
url: https://xiexvhan143.github.io/

# 作者信息
owner:
  name: 谢栩瀚
  avatar: 谢栩瀚.png
  email: 3244252455@qq.com
  cv: /resume
  # https://caihanlin.com/file/CV-HanlinCAI.pdf
  social:
    github: Xiexvhan143
    linkedin: 谢栩瀚
    bilibili: 1558822157

# 导航菜单
links:
  - title: 关于
    url: /
  - title: 作品集
    url: /portfolio/
  - title: 博客
    url: /blogs/

# 构建配置
timezone: Asia/Shanghai
future: true
highlighter: rouge
permalink: /:categories/:title

# Markdown引擎设置
kramdown:
  auto_ids: true
  toc_levels: 1..6

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 文件包含/排除规则
include: [".htaccess"]
exclude:
  - "lib"
  - "config"
  - "log"
  - "tmp"